### ISSUE TITLE
# asr_sdk

### ISSUE THREAD

**Issue by BrightGu** [mymagicpower/AIAS#2]
感谢您的分享。我在运行asr_sdk示例程序时出了点问题，不知是否是因为我遗漏了一些重要配置，麻烦您帮忙看一下，谢谢！
![7fbd5dc48d3cb759598e76a8232c224](https://user-images.githubusercontent.com/22638759/137423424-e28a5e94-50d0-4c39-bf0e-70b1527f6ebb.png)

**Comment by mymagicpower** [comment]
再pull一下代码，底层引擎更新了版本。

**Comment by mymagicpower** [comment]
代码模型路径配置确实有问题。再更新一下。
