### ISSUE TITLE
iocr

### ISSUE THREAD

**Issue by ArcherTrister** [mymagicpower/AIAS#3]
作者大大好，我通过文档部署iocr之后进行自定义模板识别，上传原图识别能到达预期的效果，但是使用在线图片识别的时候结果与标注的匹配不一致，通过对比发现 在线图片的宽高比稍大一点，请问是否是识别的图片要跟标注的图片大小一致识别才正确？

![1](https://user-images.githubusercontent.com/35516482/140629762-eb390435-105a-429b-8a1e-3f8dccab76b4.png)
![2](https://user-images.githubusercontent.com/35516482/140629782-48c70467-e6fc-4ca9-a41f-49a9e8f62da4.png)
![3](https://user-images.githubusercontent.com/35516482/140629872-1203e1f8-c669-4ede-9661-0b01d69ea203.png)

**Comment by mymagicpower** [comment]
不需要一致，结果识别错误是锚点位置选取不够分散，图像变形严重，导致仿射变换后图片没有很好的对齐。
火车票这种不适合用自定义模版，它的版式固定，适合用固定模版（只需要转正，然后按标注框识别就好）。

**Comment by ArcherTrister** [comment]
谢谢

**Comment by ArcherTrister** [comment]
谢谢
